# -*- coding: utf-8 -*-
"""DataAndResources.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13qHddls8NuYXhVr6qgmOWwAEStadVn9c
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import pandas as pd
import seaborn as sns
import matplotlib as mpl
import matplotlib.pyplot as plt
import plotly.express as px
import numpy as np

from happinessexceptionhandling import DataNotFoundException 
from happinessexceptionhandling import HeadDataNotFoundException
from happinessexceptionhandling import TailDataNotFoundException

happinessData = pd.read_csv("/content/WorldHappinessReport.csv")

class DataAndResources():
  message = "Error Occured"
  def __init__(self,happinessData):
    self.happinessData = happinessData
  
  def getHappinessData(self):
    if(happinessData.empty):
      raise DataNotFoundException(self.message)
    return self.happinessData

  def getHeadData(self,happinessData):
    if(happinessData.head().empty):
      raise HeadDataNotFoundException(self.message)
    return happinessData.head()

  def getTailData(self,happinessData):
    if(happinessData.head().empty):
      raise TailDataNotFoundException(self.message)
    return happinessData.tail()