# -*- coding: utf-8 -*-
"""HappinessExceptionHandling.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xqPYNRY_U1JJ9u4X68QHJ_0-plE77ye7
"""

class BaseException(Exception):
    def __init__(self, message):
        super().__init__(message)

class DataNotFoundException(BaseException):
  def __init__(self, message):
        message = 'Data Not found'
        super().__init__(message)

class HeadDataNotFoundException(BaseException):
  def __init__(self, message):
        message = 'Head Data Not found'
        super().__init__(message)

class TailDataNotFoundException(BaseException):
  def __init__(self, message):
        message = 'Tail Data Not found'
        super().__init__(message)